# Generated by Django 5.0.4 on 2024-12-02 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_of_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('role_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('role_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('role_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('number', 'Number'), ('email', 'Email'), ('address', 'Address'), ('extra number', 'Extra Number')], max_length=20, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Описание')),
                ('text_ru', models.TextField(null=True, verbose_name='Описание')),
                ('text_en', models.TextField(null=True, verbose_name='Описание')),
                ('text_ky', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Email_sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.EmailField(max_length=254, verbose_name='Получатель')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_ky', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Images_for_multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images_for_multimedia', verbose_name='Картинка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка на видео')),
                ('type', models.CharField(choices=[('graduates', 'Graduates'), ('video', 'Video'), ('picture', 'Picture')], max_length=20, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('avatar', models.FileField(upload_to='avatars', verbose_name='Фотография')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('bio', models.TextField(verbose_name='Био')),
                ('bio_ru', models.TextField(null=True, verbose_name='Био')),
                ('bio_en', models.TextField(null=True, verbose_name='Био')),
                ('bio_ky', models.TextField(null=True, verbose_name='Био')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет')),
                ('subject_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет')),
                ('subject_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет')),
                ('subject_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='samples', verbose_name='Файл')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='sertificates', verbose_name='Картинка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
    ]
