# Generated by Django 5.0.4 on 2026-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_remove_multimedia_graduates_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images_for_multimedia',
            options={'verbose_name': 'Мультимедиа (фото / видео)', 'verbose_name_plural': 'Мультимедиа (фото / видео)'},
        ),
        migrations.AlterModelOptions(
            name='sertificate',
            options={'ordering': ['section', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='sertificate',
            name='section',
            field=models.CharField(choices=[('general', 'Прочие награды'), ('hall_of_fame', 'В зале славы'), ('partners', 'Благодарности и грамоты партнёрам')], default='general', max_length=32, verbose_name='Раздел на странице «Награды»'),
        ),
        migrations.AddField(
            model_name='sertificate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в разделе'),
        ),
    ]
