# Generated by Django 5.0.4 on 2026-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0004_sertificate_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block_of_contact',
            options={'verbose_name': 'Блок контактов (альтернативный)', 'verbose_name_plural': 'Блоки контактов'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт (карточка на странице «Контакты»)', 'verbose_name_plural': 'Контакты (карточки)'},
        ),
        migrations.AlterModelOptions(
            name='contact_information',
            options={'verbose_name': 'Контактная строка (блок на сайте)', 'verbose_name_plural': 'Контактная информация (блоки)'},
        ),
        migrations.AlterModelOptions(
            name='email_sending',
            options={'verbose_name': 'Почта отправителя (обратная связь)', 'verbose_name_plural': 'Почта отправителя (обратная связь)'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос и ответ (FAQ)', 'verbose_name_plural': 'Частые вопросы (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'verbose_name': 'Преподаватель (демо / старый раздел)', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Документ-образец', 'verbose_name_plural': 'Образцы документов'},
        ),
        migrations.AlterModelOptions(
            name='sertificate',
            options={'ordering': ['section', 'sort_order', 'id'], 'verbose_name': 'Сертификат / грамота', 'verbose_name_plural': 'Награды и сертификаты'},
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Телефон / контакт'),
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='block_of_contact',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Телефон или другой контакт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль на сайте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль на сайте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль на сайте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль на сайте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО / должность (кратко)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО / должность (кратко)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО / должность (кратко)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО / должность (кратко)'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='type',
            field=models.CharField(choices=[('number', 'Телефон'), ('email', 'E-mail'), ('address', 'Адрес'), ('extra number', 'Доп. телефон')], max_length=20, verbose_name='Тип контакта'),
        ),
        migrations.AlterField(
            model_name='email_sending',
            name='receiver',
            field=models.EmailField(help_text='С этого адреса отправляются письма из формы обратной связи (и как получатель копии). Должна совпадать с настройками SMTP.', max_length=254, verbose_name='Почта для системных писем'),
        ),
        migrations.AlterField(
            model_name='images_for_multimedia',
            name='type',
            field=models.CharField(choices=[('picture', 'Фото'), ('video', 'Видео')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ky',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет / курс'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет / курс'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет / курс'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет / курс'),
        ),
    ]
