# Generated by Django 5.0.4 on 2026-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0006_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('image', models.FileField(blank=True, null=True, upload_to='graduates', verbose_name='Фото / изображение')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка')),
                ('label_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка')),
                ('label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка')),
                ('label_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выпускник / карточка страницы',
                'verbose_name_plural': 'Наши выпускники',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
