# Generated by Django 5.0.4 on 2026-03-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lecturepreparationmaterial_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses_programms',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='category',
            field=models.CharField(blank=True, help_text='Как рубрика в каталоге (например «Агрономия», «Цифровые навыки»).', max_length=500, verbose_name='Направление / категория'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='category_en',
            field=models.CharField(blank=True, help_text='Как рубрика в каталоге (например «Агрономия», «Цифровые навыки»).', max_length=500, null=True, verbose_name='Направление / категория'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='category_ky',
            field=models.CharField(blank=True, help_text='Как рубрика в каталоге (например «Агрономия», «Цифровые навыки»).', max_length=500, null=True, verbose_name='Направление / категория'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='category_ru',
            field=models.CharField(blank=True, help_text='Как рубрика в каталоге (например «Агрономия», «Цифровые навыки»).', max_length=500, null=True, verbose_name='Направление / категория'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='show_on_additional_education',
            field=models.BooleanField(default=True, verbose_name='Показывать в «Дополнительном образовании»'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='show_on_international',
            field=models.BooleanField(default=True, verbose_name='Показывать в «Международном сотрудничестве»'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в каталоге'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='start_info',
            field=models.CharField(blank=True, help_text='Дата старта, период набора и т.п.', max_length=255, verbose_name='Сроки / набор'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='start_info_en',
            field=models.CharField(blank=True, help_text='Дата старта, период набора и т.п.', max_length=255, null=True, verbose_name='Сроки / набор'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='start_info_ky',
            field=models.CharField(blank=True, help_text='Дата старта, период набора и т.п.', max_length=255, null=True, verbose_name='Сроки / набор'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='start_info_ru',
            field=models.CharField(blank=True, help_text='Дата старта, период набора и т.п.', max_length=255, null=True, verbose_name='Сроки / набор'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='study_format',
            field=models.CharField(blank=True, help_text='Например: очно, онлайн, смешанный.', max_length=255, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='study_format_en',
            field=models.CharField(blank=True, help_text='Например: очно, онлайн, смешанный.', max_length=255, null=True, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='study_format_ky',
            field=models.CharField(blank=True, help_text='Например: очно, онлайн, смешанный.', max_length=255, null=True, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='courses_programms',
            name='study_format_ru',
            field=models.CharField(blank=True, help_text='Например: очно, онлайн, смешанный.', max_length=255, null=True, verbose_name='Формат обучения'),
        ),
        migrations.AlterField(
            model_name='lecturepreparationmaterial',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Текст ссылки (например «Скачать»). Если пусто — на сайте подставится общая подпись «скачать».', max_length=255, null=True, verbose_name='Подпись (кнопка)'),
        ),
        migrations.AlterField(
            model_name='lecturepreparationmaterial',
            name='button_text_ky',
            field=models.CharField(blank=True, help_text='Текст ссылки (например «Скачать»). Если пусто — на сайте подставится общая подпись «скачать».', max_length=255, null=True, verbose_name='Подпись (кнопка)'),
        ),
        migrations.AlterField(
            model_name='lecturepreparationmaterial',
            name='button_text_ru',
            field=models.CharField(blank=True, help_text='Текст ссылки (например «Скачать»). Если пусто — на сайте подставится общая подпись «скачать».', max_length=255, null=True, verbose_name='Подпись (кнопка)'),
        ),
    ]
