# Generated by Django 5.0.4 on 2026-03-22 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_courses_programms_catalog_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission_date',
            options={'verbose_name': 'Срок приёмной кампании', 'verbose_name_plural': 'Сроки приёмной кампании'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание (файл)', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='scholorship_grant',
            options={'verbose_name': 'Стипендия или грант', 'verbose_name_plural': 'Стипендии и гранты'},
        ),
        migrations.AlterField(
            model_name='admission_date',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='courses_programms',
            name='type',
            field=models.CharField(choices=[('student', 'Для слушателей / студентов'), ('lecturer', 'Для преподавателей')], max_length=25, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='file',
            field=models.FileField(upload_to='schedule', verbose_name='Файл расписания'),
        ),
        migrations.AlterField(
            model_name='scholorship_grant',
            name='type',
            field=models.CharField(choices=[('scholorship', 'Стипендия'), ('grant', 'Грант')], max_length=255, verbose_name='Тип'),
        ),
    ]
