# Generated by Django 5.0.4 on 2026-06-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_delete_scholorship_grant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses_programms',
            options={'ordering': ['sort_order', 'id']},
        ),
    ]
