# Generated by Django 5.0.4 on 2024-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('background', models.FileField(upload_to='events', verbose_name='Фон')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('duration_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('duration_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('duration_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('location_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=25, verbose_name='Тип мероприятия')),
            ],
        ),
    ]
