# Generated by Django 5.0.4 on 2026-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие / мероприятие', 'verbose_name_plural': 'События и мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.FileField(upload_to='events', verbose_name='Фон (изображение)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место / ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место / ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место / ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место / ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('offline', 'Очное'), ('online', 'Онлайн')], max_length=25, verbose_name='Формат'),
        ),
    ]
