# Generated by Django 5.0.4 on 2024-12-02 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.FileField(upload_to='news', verbose_name='Картинка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Main_page_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_1', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page1', to='news.news', verbose_name='Новость 1')),
                ('news_2', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page2', to='news.news', verbose_name='Новость 2')),
                ('news_3', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page3', to='news.news', verbose_name='Новость 3')),
                ('news_4', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page4', to='news.news', verbose_name='Новость 4')),
            ],
        ),
    ]
