# Generated by Django 5.0.4 on 2026-03-22 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_page_news',
            options={'verbose_name': 'Новости на главной странице', 'verbose_name_plural': 'Новости на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='main_page_news',
            name='news_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page1', to='news.news', verbose_name='Слот 1 (главная)'),
        ),
        migrations.AlterField(
            model_name='main_page_news',
            name='news_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page2', to='news.news', verbose_name='Слот 2 (главная)'),
        ),
        migrations.AlterField(
            model_name='main_page_news',
            name='news_3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page3', to='news.news', verbose_name='Слот 3 (главная)'),
        ),
        migrations.AlterField(
            model_name='main_page_news',
            name='news_4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_page4', to='news.news', verbose_name='Слот 4 (главная)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
